/**
 * Appplatform backend
 * App platform
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Team} from "./team";


export class Player {
  birthDate?: string;
  firstName?: string;
  id?: number;
  lastName?: string;
  nationality?: string;
  playerNumber?: number;
  teams?: Array<Team>;

  getFullName(): string {
    return this.firstName + ' ' + this.lastName;
  }
}
